### ISSUE TITLE
[Feature]: Add accounts I don't follow to lists

### ISSUE THREAD

**Issue by herr-schaft** [mastodon/mastodon-ios#1071]
### Description

Lists can be a great way to keep tabs on people or things who or that I don't necessarily want to see in my main feed.

### Suggested Solution

Please let me add accounts I don't follow to a list.

**Comment by j-f1** [comment]
Due to the way Mastodon works, you’ll need to follow people in order to have them on a list. However, https://github.com/mastodon/mastodon/pull/22048 adds support for “exclusive lists” which hide their members from your home timeline. This would probably be implemented as part of adding list support, which is not currently present.
