### ISSUE TITLE
[Feature]: Please remove me from "Find People to Follow"

### ISSUE THREAD

**Issue by Akkiesoft** [mastodon/mastodon-ios#1085]
### Description

For a few days, (perhaps) lots of newbie follow me from "Find People to Follow" by app.

example: https://mastodon.social/@kentaj45/following

But they follow me because "the app recommended me".
Probably no one is actually interested in me.
They don't set up a profile, don't introduce themselves.
I'm not interested in following them.

### Suggested Solution

* Remove me from "Find People to Follow" list OR I would like a setting that allows me to opt out of the list.
* Force profile settings "before following accounts" during account setup (I don't know if it's already that way.)

**Comment by zeitschlag** [comment]
@Akkiesoft I'm sorry for you popularity, but from my perspective, this is not an issue of the iOS-app. That's why I'll close this issue.

You can change in your profile-settings if you do want to show up in that "popular on mastodon"-list:

<img width="627" alt="Screenshot 2023-07-04 at 14 45 44" src="https://github.com/mastodon/mastodon-ios/assets/2580019/e3630696-abd6-4e60-89fa-136521f1183e">

Remove the checkmark.

On your server you linked in your Github-profile, you should find the setting here:

https://social.mikutter.hachune.net/settings/profile
