### ISSUE TITLE
[BUG] Data is rendered incorrectly when building using Xcode 16 / iOS 18 in Release Configuration

### ISSUE THREAD

**Issue by kimar** [mastodon/mastodon-ios#1348]
# The Issue

We recently noticed that, when building a release using Xcode 16 on macOS 14, the App is in a broken state with corrupt post messages.

This does only occur when using the `Release` Configuration, which makes me assume that it's related to some sort of compiler optimization going wrong, potentially introduced by Xcode 16.

## Suspects

* [MetaTextKit](https://github.com/TwidereProject/MetaTextKit) or it's underlying XML parsing library
  * This library is used throughout our codebase and has a significant impact on it.

# Examples

## Debug Build (Working as expected)

Everything looks in order here...

| Post | MetaContent | Attributed String |
|---|---|---|
| <img width="559" alt="Bildschirmfoto 2024-10-09 um 14 49 31" src="https://github.com/user-attachments/assets/f9c5cfdf-7c47-4b37-9892-f52fff0ba9ea"> |<img width="1047" alt="Bildschirmfoto 2024-10-09 um 14 49 01" src="https://github.com/user-attachments/assets/cc8b6141-ff3a-44e6-839b-6ee4d83b7358">|<img width="1042" alt="Bildschirmfoto 2024-10-09 um 14 47 01" src="https://github.com/user-attachments/assets/cd37f89a-cce7-41eb-b9a4-aaaadf64d3b5"> |

## Release Build (**Not** working as expected)

Looks like we got a problem here...

| Post | MetaContent | Attributed String |
|---|---|---|
| <img width="559" alt="Bildschirmfoto 2024-10-09 um 14 51 36" src="https://github.com/user-attachments/assets/47cc39fd-0a27-4443-bc05-cabdcd50cbf9"> | <img width="1043" alt="Bildschirmfoto 2024-10-09 um 14 45 52" src="https://github.com/user-attachments/assets/2f5fd58d-ef62-451c-aea8-4a2fdd6c91dd"> | <img width="1042" alt="Bildschirmfoto 2024-10-09 um 14 47 01" src="https://github.com/user-attachments/assets/b2e75b12-98c4-4795-bddd-dc1dd918754c">|

**Comment by vcsjones** [comment]
Memorializing a [conversation on Mastodon](https://mastodon.online/@eliperkins/113278015138715599)...

GitHub had a similar issue that we (@eliperkins) tracked down to the Fuzi dependency, which MetaTextKit has a [dependency on](https://github.com/TwidereProject/MetaTextKit/blob/2959963fbcb77808bd9a167ea35d21e25304c358/Package.swift#L24).

It presented slightly differently for us - instead of garbled texted, the text did not render at all. Otherwise the same: only on  Xcode 16, and only when building Release. If the issue is improper memory management then that would explain the slightly asymmetric behavior.

Eli's Post contains the work-around, but might be tricker as a dependency-of-a-dependency in this case.

**Comment by eliperkins** [comment]
If it is the same bug, perhaps changing this `HTMLDocument(string:)` call to `HTMLDocument(buffer:)` might be a short-term solution? 

https://github.com/TwidereProject/MetaTextKit/blob/2959963fbcb77808bd9a167ea35d21e25304c358/Sources/MastodonMeta/MastodonMetaContent%2BNode.swift#L77

**Comment by kimar** [comment]
Thank you all for your help, this was very useful, we've decided to use [our own fork of MetaTextKit](https://github.com/mastodon/MetaTextKit) for the time being while working on a more sustainable solution.
