### ISSUE TITLE
Update destruction menu option UX behavior

### ISSUE THREAD

**Issue by MainasuK** [mastodon/mastodon-ios#145]
The destruction menu action likes "Block" needs to alert the user with the action description.

Title: Action Name
Message: The action will do something
Button: Cancel / Action

**Comment by tejuamirthi** [comment]
Hey @MainasuK 
I still see it in TODO. Is this completed now? 
I would like to contribute to this project, hope you are open for outside contributors. 
Please let me know if there are any issues that needs attention or to be fixed. Any help will be highly appreciated!

P.s: I searched through the issues, not sure which can be taken up right away.

**Comment by tejuamirthi** [comment]
Hey @MainasuK, I think it's safe for us to close this issue. There are other issues as well which can be closed because they were fixed.

Also, please let me know if there is any other features, bug that needs to be fixed. The issues tab list is quite long and I'm not sure about which things are already fixed. Thanks!
