### ISSUE TITLE
Not possible to login to Mastodon server with limited federation mode enabled

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon-ios#184]
From TestFlight feedback. Not sure why.

**Comment by exstral** [comment]
Hi, I'm also seeing this issue with a limited federation server I'm an admin of. I'm using the app on an iPhone XR with app version 1.0.7. When I enter the URL `queer.haus` in the server search box the spinner is shown endlessly loading. I've checked and the instance endpoint does return valid json.

https://queer.haus/api/v1/instance

**Comment by MainasuK** [comment]
> Hi, I'm also seeing this issue with a limited federation server I'm an admin of. When I enter the URL `queer.haus` in the server search box the spinner is shown endlessly loading. I've checked and the instance endpoint does return valid json.
> 
> https://queer.haus/api/v1/instance
> 
> I'm using an iPhone XR with Mastodon app version 1.0.7 and server side Hometown version v1.0.5+3.4.0. Our instance is running both with LIMITED_FEDERATION_MODE and AUTHORIZED_FETCH enabled.

@exstral  Sorry for the late reply.

If your server endpoint could access under your network (maybe via VPN?). The app should works. Just try view "https://queer.haus/api/v1/instance" in the Safari app and verify the server responds with valid JSON. 

Please open a new issue if the problem is not resolved.
