### ISSUE TITLE
View Local and Fediverse instance timelines

### ISSUE THREAD

**Issue by cdmnky73** [mastodon/mastodon-ios#221]
Add the ability to see the local instance and fediverse timelines via more buttons on the bottom

**Comment by OddHouseGames** [comment]
This was a very jolting change.

If the ability to choose what timeline you are viewing has been removed, it should make it clear what timeline/content you are seeing?

It's also better to keep parity with the web app, or it could be a subtle feature like long press on the home icon to change it.

Either way, some clarity would be great!

**Comment by Gargron** [comment]
The omission is intentional and I do not intend to add these types of timelines into the app. They might have made sense for early Mastodon in November 2016 when there were less than 20k people total and all from a homogenous demographic but nowadays the signal to noise ratio makes them a liability in almost every aspect. I might write more on the topic on the blog.

**Comment by cdmnky73** [comment]
What's the point of even joining a custom instance then? If your end goal was to make a complete twitter clone, why even make make Mastodon decentralized in the first place?

The *point* of a local timeline is to allow an instance to be set up around a particular theme or culture, that way one can communicate in that "homogenous demographic" you reference. The Fediverse as a whole is diverse *because* one can take advantage of a local instance timeline, while also follow friends from other instances. As it stands right now, with this app, the only difference between instances that a user will notice is the emoji picker.

It's incredibly distressing that you're putting this sort of mindset into developing Mastodon software nowadays when you yourself said years ago that there shouldn't be any default instance or app in order to encourage more diversity on the platform. I honestly had a bit of hope that developing an iOS app would be a good idea given how barren the ecosystem is compared to Android, but I certainly won't be investing any time into it if I can't even interact with my own instance's timeline, the *reason* I use the Fediverse over Twitter.

**Comment by snoozysoft** [comment]
Man makes decentralized open source social network.
Man creates first instance with a name that immediately complicates the concept of the network.
Man finds first instance growth too fast and cannot moderate.
Man continues to complain about such a problem, but refuses to disable sign ups on first instance or even moderate it, and instead flees to a new one.
Man finds new one's growth is also too fast and cannot moderate either.
Man creates new mobile app for his social network and ignores two basic core concepts he put into the network itself, the two things that _literally set it apart and is half the point of the network._
Man is upset when someone points out this is contradictive and threatens to blog about it.

Seriously though: what the hell are you even doing? How many times has the wider Mastodon community had to wade in and tell you to piss off with your idiotic ideas that completely ruin the entire point and purpose of your own software just so you can chase some horrible ideal of "Twitter but better" - which, by the by, it has already completely failed at - that _literally nobody wants_?  Just stop. The fact that you feel the need to create a "official" Mastodon application is fucking disgusting to begin with because it throws out the idea of community and people making Mastodon theirs. What's next? Employing API limits on unofficial applications? You may as well, if you want to be a Twitter clone so badly. You should have stood down as the maintainer of this project a long time ago, you are clearly unfit to be running it anymore.

**Comment by Gargron** [comment]
The fediverse is diverse because you can follow anyone from any server. The local timeline plays no role in that and doesn’t even exist in ActivityPub as a concept. Being able to choose a different server has always been about trust for the service provider and rules. I’m fully aware that for some people the local timeline is basically like a Slack or IRC chatroom and for this reason the feature cannot be removed from Mastodon in the foreseeable future, but it was never meant to be that, and I see no reason to add it to an app that targets new users rather than existing ones. 

The app streamlines many concepts that became less concise due to incremental implementation. For example, the unlisted visibility, which was added in response to people complaining about the local timeline being added, has a confusing place in the visibility hierarchy - “public in all senses except it doesn’t show up in a specific place I’m not yet sure why i should care about”. The other visibilities are much easier to grasp without it being in the list. 

The “local” timeline makes the concept of “you can follow anyone from any server” less concise because suddenly you do care what server you are on. Also has people mistaking it for geographical location, which is understandable when the concept of servers is still new. In UX tests with randomly selected, non-technical people, stumbling upon local or federated timelines has predominantly led to frustration either through language barriers, spam, or not safe for work content. I know that we might disagree about the size of server we have in mind or what constitutes a big server, but I think you’ll agree that even on a small and perfectly moderated server at least 2 of the 3 issues are likely to occur, if not in one timeline then another. And, unless you advocate for an “upload filter” type system, no moderation will be able to prevent exposure to spam and offensive content at least temporarily, at least in an open system which is what we’re focusing on. In short, these types of timelines are hurting Mastodon’s adoption and present a risk for the app on the App Store since Apple will hold the app accountable for user generated content. 

Being rude about it will not help your case. That’s not directed at the commenter above but the one whose comment I had to delete. Nobody is forcing you to use or even like this app. As in the original announcement on the blog, we’re not trying to take the cake from existing 3rd party apps but to make the cake bigger for everyone by excelling where those apps fail.
