### ISSUE TITLE
Missing block domain dropdown option on profiles

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon-ios#364]

**Comment by callionica** [comment]
Yes, please allow iOS users to block domains. I thought this feature existed in Mastodon and was confused when it didn't show up in the menu. Other users may not complain of its absence because they don't even know it's a possibility. It's essential for all the Twitter-as-Mastodon, RSS-as-Mastodon, and aggregator/republisher domains that keep popping up.
