### ISSUE TITLE
[BUG] Cannot login to an instance missing in the list

### ISSUE THREAD

**Issue by tobsen** [mastodon/mastodon-ios#371]
I want to login to social.chaos. When I search the list for chaos.social, there is no result. Is there an other option to login? Do I miss something?

**Comment by binaryanomaly** [comment]
Same here for mastodon.technology not in the list and
can’t find a way to enter an url?

**Comment by Gargron** [comment]
Just enter the address into the search field and it should pop up

**Comment by binaryanomaly** [comment]
Indeed it works like that, thanks.
For some reason it didn't work when I tried it before, maybe it was just slow.
Also not very intuitive more of a trial and error experience.

**Comment by tobsen** [comment]
Thanks!
Running the App on a M1 Mac, the login popup does not work. It opens Safari and nothing happens.

**Comment by kadin2048** [comment]
I just tested this and I'm still seeing the problem.  Entering a valid Mastodon instance into the Search box (I tried using "mastodon.sdf.org") results in a spinning beach ball forever.  It is not possible to log into the specified instance, because nothing ever pops up as a result of the search.

Tested:
Mastodon 1.3.1 Build 113
iOS 15.4.1
iPhone SE

**Comment by MainasuK** [comment]
Enter the server full domain then the app should grab the info directly from it.

**Comment by MainasuK** [comment]
<img width=300 src="https://user-images.githubusercontent.com/7940186/167239079-bd04aa7b-ee7e-4bda-bc13-81da7344ea31.png" />

@kadin2048 Hello, please try to wait a seconds and check the network connection. It's  should works.
