### ISSUE TITLE
[BUG] Close Fullscreen Video

### ISSUE THREAD

**Issue by smeagolli** [mastodon/mastodon-ios#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I encountered, when watching a video on mastodon iOS (iphone X) in fullscreen there is no possibility to close the window. So you can only close the whole app and restart.

### Expected Behavior

A close button would be nice.
Keep up the good work!

### Steps To Reproduce

1. open any video in the app
2. try to close it 😁
3. …
4. (decide you watch too many videos, anyways)
5. (have an epiphany on how to prevent the climate catastrophe)
6. (quit doomscrolling and use your time for the greater good)

### Environment

```markdown
- Device: iphone X
- OS: iOS
- Version: 1.4.5
- Build:
```

**Comment by paulywill** [comment]
Can confirm... sliding down appears the only way to exit full screen video.

Would also agree a close button should be standard.

**Comment by j-f1** [comment]
This is a complicated UX to handle. Ideally, tapping on a video would open iOS’s native full screen player (which handles interactions quite well). However, Mastodon allows posts with mixed video + photos, so you need to be able to swipe between them (which can’t be done with the default full screen player). There’s also the complication that the inline video player iOS provides has a full screen button baked in, which doesn't really make sense for our use case. Fixing this requires either implementing a custom video player UI (which would be unfortunate since the current UI gives us so much for free) or coming up with an alternate interaction model that works around the limitations of full screen video.

**Comment by jinsu35** [comment]
I think this issue has been resolved.

**Comment by StephanEggermont** [comment]
Actually, all interactions with embedded video need to be revisited and fixed. That needs a design workshop though, not separate issues

**Comment by KleinDevDE** [comment]
I guess this is the same error as in #955

That the Alt Bar partially covers the close button and therefore you can't reach it.
