### ISSUE TITLE
[BUG] Accessibility/VoiceOver: Navigation trap at the top of a post detail view

### ISSUE THREAD

**Issue by ericyahhh** [mastodon/mastodon-ios#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Go to your timeline view
- Turn on VoiceOver
- Swipe right to select a post
- Double tap to open its detail view
- VoiceOver focus will be at the back button √
- Swipe right 
- VoiceOver focus will be at the "Post from..." title √
- Swipe right
- Voiceover focus doesn't jump to the reply button. You'll just hear a "disabled" sound
- NOTE: This seems to be only happening when opening someone else' post, not posts of yourself

![IMG_028C7CE59460-1](https://user-images.githubusercontent.com/1116348/200837557-10ea9b27-c3de-4824-8112-e821f973f293.jpeg)

### Expected Behavior

I expect the VoiceOver focus to seamlessly move through the UI by swiping right on a detail view/post detail 

### Steps To Reproduce

See above

### Environment

```markdown
- Device: iPhone 12 mini
- OS: iOS 16.1
- Version: 1.4.5
- Build: 144
```

**Comment by j-f1** [comment]
I’ve noticed this too, and also noticed that explicitly tapping on the “Post from Laszlo” title seems to fix the issue since you can navigate forward after that. I tried to work around the issue with #491 by jumping focus to the post content, but there are still cases where you can get into this weird state. Have you seen this sort of issue elsewhere before? Do you have any ideas for how it could be fixed? (I tried looking with Accessibility Inspector but was unable to identify the issue)

**Comment by ericyahhh** [comment]
This exact case seems to be fixed now, thanks for fixing this @j-f1 👏 

However, there's still a minor case where a user could end up in this "trap" so I wouldn't close that issue:
- open the app and the timeline
- enable Voiceover
- move the focus to a post and double tap
- go to the reply button and double tap
- go to the cancel button double tap
- focus will be on "discard" now
- double tap to confirm
- Now you land on the post details page again and the focus will be set to the back button
- now swipe right to go to the next elements
-> you cannot go further than "post of ..." as described in the original issue
