### ISSUE TITLE
App Install Dialog overstates needed access

### ISSUE THREAD

**Issue by cyclingsafety** [mastodon/mastodon-ios#580]
Just made a GitHub account to report this so first-timer.  Setting up an account in Mastodon on IOS needs to state on the same line that “Everything” refers specifically to the Mastodon account and NOT everything on the user’s device.  If you want it to be comfortable to new users, don’t make things look scarier than they need to be.

![image](https://user-images.githubusercontent.com/118130711/201539032-e98a2766-883d-4403-bdca-d7879939314b.png)

**Comment by zeitschlag** [comment]
Hey @cyclingsafety, thank you for signing up and, of course your feedback!

Although it might seem to be an issue with the iOS-app, it has to do with the login-mechanism (OAuth2), that [Mastodon](https://github.com/mastodon/mastodon/) (the server-software) provides. You will see the same wording also on Android or any other client, that wants to login into your account. So maybe you can open another issue there, so that the people can take care of it? cc @Gargron
