### ISSUE TITLE
[FEATURE] Edit Toots

### ISSUE THREAD

**Issue by sammcj** [mastodon/mastodon-ios#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the mobile app there is no button to edit Toots once sent

### Expected Behavior

The same as the web interface - have an edit button to edit your tent Toots

### Steps To Reproduce

1. Send a Toot
2. Try to edit it in the app

### Environment

```markdown
- Device: iPhone 14 Pro
- OS: 16.x
- Version: 1.4.5 (latest stable)
- Build:
```

**Comment by giuliohome** [comment]
Subscribed and 👍
I just want to add (especially for Android implementation) that the text while user is writing should be persisted somewhere, temporary (until the edit is published, eventually).
So that when one switches to another activity and returns back to editing, the partially entered text won't be lost.
Actually this comment of mine could be considered also as an issue of the "publishingToot" feature (maybe already opened for that?) and even of the current web app.

**Comment by FediVideos** [comment]
This issue can be closed now as v1.5 has toot editing?

**Comment by giuliohome** [comment]
Thank you!!!

**Comment by giuliohome** [comment]
Cool, where is the related code? (e.g. I see the Android release https://github.com/mastodon/mastodon-android/releases/tag/v1.1.4 "_You can now edit your posts and view post edit history_" with 523 commits...)
Ok, I guess it is a long story starting from https://github.com/mastodon/mastodon-android/commit/ff52c37868dc0f776e25d412fd9489f41a9bcdfb related to the ComposeFragment, etc...


What about momentarily saving the edited text?
https://github.com/mastodon/mastodon/issues/22797
It seems to be solved too.
