### ISSUE TITLE
[BUG] Use “boost” instead of “reblog”

### ISSUE THREAD

**Issue by rrgeorge** [mastodon/mastodon-ios#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app ui uses the term “reblog/reblogged” instead of the term “boost/boosted”.
This is inconsistent with the web ui. 

### Expected Behavior

The app ui should use consistent terminology with the web ui.

### Steps To Reproduce

1. View any post
2. Observe “## reblogs” at the bottom
Or
1. View any boosted post
2. Observe “** reblogged” at the top

### Environment

```markdown
- Device: iPhone 12 Pro
- OS: iOS 16.2
- Version: v1.4.7
- Build: 196
```

**Comment by ushuz** [comment]
What about "retoot"?

**Comment by Yonodactyl** [comment]
Don't hate me, but I think the word `retoot` feels a little derogatory (even though it's a made up word).

I do agree with the initial thoughts here of being consistent and on brand!

**Comment by rrgeorge** [comment]
> What about "retoot"?

While I think toot is a kinda fun and silly colloquialism, it’s no longer the official label, so it shouldn’t be used in the official app.

**Comment by Yonodactyl** [comment]
The new phrasing goes by `posts` now, right?

**Comment by rrgeorge** [comment]
I suppose that’s right. The main thing is the “Toot!” button is now “Publish!”

**Comment by rrgeorge** [comment]
It’s even more confusing because the push notification says “boosted”

**Comment by Yonodactyl** [comment]
Sounds like things could use an all around reformatting to make sure it follows the new naming conventions!

**Comment by FediVideos** [comment]
Yes, please do use "boost" instead of "re-blog". I have been on Mastodon for several years and never ever seen someone talk about re-blogging, it is always "boosting".

It is confusing for new people when they are told about boosting and there is no boost option mentioned. If this app is meant for new people, it's especially important to be consistently using the word "boost".

**Comment by todoneunl** [comment]
> Yes, please do use "boost" instead of "re-blog". I have been on Mastodon for several years and never ever seen someone talk about re-blogging, it is always "boosting".
> 
> It is confusing for new people when they are told about boosting and there is no boost option mentioned. If this app is meant for new people, it's especially important to be consistently using the word "boost".

Agreed. In the web-app it is and always has been named _boosted_, and people are used to that. It's a bad idea to have different names of features on different devices, that will confuse people.

Same goes btw for the Android app.

**Comment by Gargron** [comment]
Correction, in the web app it was not always “boosted”, that’s flavour text added around 2017 or late 2016 similar to “toot” (since removed). It was “reblogged” originally and remains so in the code and API. There are disadvantages to “boost”: it is slang for theft, and facebook uses it to mean paying to promote a post. It is also simply less familiar than reblog. I didn’t want to use “boost” in a new app with a fresh slate.

**Comment by todoneunl** [comment]
@Gargron I follow your reasoning, but it is not 2017 anymore. You have to understand that you can't just change familiar terms for millions of people, especially now Mastodon has become mainstream. The change of _toot_ to _publish_ was received with very mixed feelings, so let's not make that mistake again. Because this and the Android apps are official apps, people expect it to use the same terminology. So with your reasoning I understand you want to change _boost_ to _reblog_ in the web-app as well. Better making these important decisions with the input of the community and not you alone. That will give the project a bad reputation and nobody wants that (well except one well known rocket owning person).

P.S. (well actually it's not, because very important): You also have to consider the translations. Not all terms can translated literally in a lot of languages. So translators have to be creative to fix that problem. So do I really don't know how to translate _reblog_ in Dutch. Boost is a familiar word in Dutch.

**Comment by rrgeorge** [comment]
@Gargron The web ui uses “boost”, and according to the screenshots in the Play store so does the Android app. The iOS app is the only one that doesn’t. 

> There are disadvantages to “boost”: it is slang for theft, and facebook uses it to mean paying to promote a post

Boost literally means “help, encourage, raise up, or lift”. 
Use as a slang for “steal” is not very common. 

“Re-blog” also is cumbersome to say, people will continue to say “boost”, you even do on your posts. Having different terms in one app than what people use is confusing for users.

**Comment by FediVideos** [comment]
> Correction, in the web app it was not always “boosted”, that’s flavour text added around 2017 or late 2016 similar to “toot” (since removed). It was “reblogged” originally and remains so in the code and API. There are disadvantages to “boost”: it is slang for theft, and facebook uses it to mean paying to promote a post. It is also simply less familiar than reblog. I didn’t want to use “boost” in a new app with a fresh slate.

Native English speaker here living in an English speaking country, I have never ever heard anyone use the term "boost" for theft, either people I know or people in the media. If you say boost in English it is always assumed to mean giving energy to something, lifting it up (like a booster rocket, or a booster vaccination, or a booster seat).

Reblog doesn't make much sense because this isn't a blog. Yes technically it's "microblogging" but no one calls it that outside the techy community. To most non-techy people, a blog is a long form text site, so it's confusing to use that term on a short form social network app.

As people are already calling it boost, the lack of consistency is confusing for new people. They see existing members refer to it as boosts, but nothing in the iOS app reflects this term. This isn't a blank slate situation, there were already millions of registered users on Mastodon when the official app was introduced. Millions have joined since then, but they will naturally take their cues from existing members' terms.

**Comment by rrgeorge** [comment]
This appears to be resolved.
