### ISSUE TITLE
First character in a reply should be capitalized

### ISSUE THREAD

**Issue by Scenario** [mastodon/mastodon-ios#756]
### Steps to reproduce the problem

Reply to any post. 

### Expected behaviour

First character capitalized

### Actual behaviour

First character is not capitalized

### Detailed description

The reply field is pre-populated with the tags of who you are replying to. But that is rarely part of your intended reply. As is, the first letter of the sentence you type is lowercase, which is grammatically incorrect. It takes extra effort to go change it.

### Specifications

Latest iOS

**Comment by Der-K-2000** [comment]
Wrong repository → https://github.com/mastodon/mastodon-ios

**Comment by j-f1** [comment]
As far as I know, there is no way to manually toggle the Shift key on the keyboard using public APIs, and [there doesn’t seem to be a relevant option for this](https://developer.apple.com/documentation/uikit/uitextautocapitalizationtype) in the set of auto-capitalization types. That said, maybe there’s a way to hook into iOS’s interpretation of “sentences” to trick it into seeing the @mentions as a “sentence” and therefore enabling the shift key? Alternatively, we could override the autocapitalization type to `words` if the post content matches the initial content, so that the first word would be auto-capitalized before switching back to sentence capitalization.
