### ISSUE TITLE
[BUG] [iPadOS] Cannot scroll to bottom of composition box

### ISSUE THREAD

**Issue by davmillar** [mastodon/mastodon-ios#946]
While replying in a thread on iPadOS, I am unable to scroll to the bottom of the composition box to see what I am typing.

Using the TestFlight version of the app, v1.4.12 (268)

https://user-images.githubusercontent.com/576958/219967863-c96670c2-3511-4067-bd9b-616bc08ca782.MOV

**Comment by j-f1** [comment]
Will be fixed when https://github.com/mastodon/mastodon-ios/pull/909 is merged.

**Comment by wayneca** [comment]
This is exactly what bug #890 looks like.  In that one, you cannot scroll to the bottom of an image that you are inserting, so cannot see the overlay on the image at the bottom where you need to get to in order to insert "alt" text for people with limited vision.

I have 2 predictions about this bug (I'll try these as soon as I can):
1.  The same bug reported here will happen if you have an attached physical keyboard, so there is plenty of room, with no keyboard in the way,
2.  If you pinch the keyboard with 2 fingers to make it switch to the smaller keyboard, the bug won't happen.

#909 is a proposed fix for that alt text bug that explains what causes the problem and includes code to fix it.

**Comment by wayneca** [comment]
I tried it on an iPad Air (4th gen) with iPAD)S 16.3.1 and I see the bug you reported.  Also, the 2 things I predicted above also happen.  The bug doesn't happen if you pinch the virtual keyboard to make it small and the bug does happen when there is a physical keyboard present and there is plenty of room.  The buttons are placed as if there is a big virtual keyboard when it isn't there and there is plenty of room if the virtual keyboard is set to be big if it was there.

The alt bug is a bad bug for people with limited vision because they may need to have the virtual keyboard big in order to see it and then they cannot enter the alt text that others with low vision need.
