### ISSUE TITLE
[BUG] Cannot Exit Videos 

### ISSUE THREAD

**Issue by Touuubie** [mastodon/mastodon-ios#955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening a video in the Mastodon App, I have found myself unable to exit the fullscreen mode by clicking on the “x” button. The only way to exit is to close the entire app. 

### Expected Behavior

Hitting the button should close the video. 

### Steps To Reproduce

1. Open a video
2. Tap the close button 
3. Tap the close button 
4. …

### Environment

```markdown
- Device: Apple iPhone 13
- OS: 16.2
- Version: v1.4.11
- Build: 265
```

**Comment by j-f1** [comment]
If you swipe down on the video it should close (but this does need to be better)

**Comment by FediVideos** [comment]
I've had several people today ask me how to exit videos, swiping down doesn't help them. One of them mentioned a problem with the Alt Text button covering the X button?

**Comment by KleinDevDE** [comment]
> I've had several people today ask me how to exit videos, swiping down doesn't help them. One of them mentioned a problem with the Alt Text button covering the X button?

I own the iPhone 13 Mini.
Mastodon version 2023.9 (324)

I can't close videos either with the button.
I have the same problem with the Alt Bar.

The ALT bar overlaps the close button, which is why you can't press it.
The same is with the volume button on the top right.
But I can close them by swiping down.

Here an example as screen recording and screenshots.
This is the post with the video, if you guys need it: https://bildung.social/@empathroet/110593927096520919


![IMG_5570](https://github.com/mastodon/mastodon-ios/assets/13904220/5924967e-36c1-41f8-bcb1-abdd53d4c8b0)
![IMG_5571](https://github.com/mastodon/mastodon-ios/assets/13904220/169b901d-23bf-47fa-bb63-b47ea1eefc2b)

https://github.com/mastodon/mastodon-ios/assets/13904220/d178848f-391b-4569-b10c-cd7e82f33334
